set guioptions-=T "disable menu bar

" Default to light background
set background=light
" Silver for light background
if &background == 'light'
    hi normal guibg=white
endif
" Black for dark background
" if &background == "dark"¬
"     hi normal guibg=black¬
" endif

set guifont=Monaco:h11

"colorscheme molokai
