" Start Pathogen
"filetype off 
"call pathogen#helptags()
"call pathogen#runtime_append_all_bundles()

source ~/.vim/config/global.vim
source ~/.vim/config/bindings.vim
source ~/.vim/config/visual.vim
source ~/.vim/config/abbreviations.vim

" Read local file for custom configs
if filereadable(expand("~/.vim_local"))
    source ~/.vim_local
endif
